In [26]:
import pandas as pd
import matplotlib.pyplot as plt

shopping_data  = pd.read_csv('data/raw/shopping.csv')

In [27]:
shopping_data.head()

,Customer ID,Age,Gender,Item Purchased,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Shipping Type,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,3475,NaN,Male,Jacket,30.904467,Maine,M,Burnt orange,Fall,4.0,Standard,No,0,Credit Card,NaN
1,3698,21.0,Female,Backpack,31.588259,NaN,L,Turquoise,Winter,2.0,Express,No,1,Credit Card,Monthly
2,2756,31.0,Male,Leggings,24.231704,Nevada,M,Terra cotta,Winter,4.0,Standard,No,0,Credit Card,NaN
3,3340,NaN,Male,Pajamas,33.918834,Nebraska,M,Black,Winter,NaN,Standard,No,2,Credit Card,Bi-Weekly
4,3391,38.0,Male,Sunglasses,36.545487,Oregon,S,Aubergine,Summer,NaN,Standard,No,0,Credit Card,NaN

In [28]:
shopping_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3510 non-null   float64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Purchase Amount (USD)   3900 non-null   float64
 5   Location                3510 non-null   str
 6   Size                    3900 non-null   str
 7   Color                   3900 non-null   str
 8   Season                  3900 non-null   str
 9   Review Rating           1431 non-null   float64
 10  Shipping Type           3900 non-null   str
 11  Promo Code Used         3900 non-null   str
 12  Previous Purchases      3900 non-null   int64
 13  Payment Method          3900 non-null   str
 14  Frequency of Purchases  1560 non-null   str
dtypes: float64(3), int64(2), str(10)
memory usage: 457.2 KB

In [61]:
shopping_data['Review Rating'].describe()

count    1431.000000
mean        3.904962
std         1.105952
min         1.000000
25%         4.000000
50%         4.000000
75%         5.000000
max         5.000000
Name: Review Rating, dtype: float64

In [29]:
shopping_data.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3510.000000,3900.000000,1431.000000,3900.000000
mean,1950.500000,34.256695,38.708329,3.904962,5.841538
std,1125.977353,10.616340,11.504923,1.105952,5.843695
min,1.000000,18.000000,11.392520,1.000000,0.000000
25%,975.750000,26.000000,29.332617,4.000000,1.000000
50%,1950.500000,33.000000,36.953004,4.000000,4.000000
75%,2925.250000,41.000000,48.739596,5.000000,9.000000
max,3900.000000,75.000000,69.567481,5.000000,20.000000

In [30]:
shopping_data['Payment Method'].unique()

<StringArray>
['Credit Card', 'Bank Transfer', 'Cash', 'Debit Card', 'PayPal', 'Venmo']
Length: 6, dtype: str

In [38]:
'''The code below ranks the popularity of clothing items by color during the Winter season.'''
shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Color', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Fall', ascending = False)

Season,Color,Fall,Spring,Summer,Winter
4,Brown,4549.173005,219.926643,187.804524,4453.445747
13,Ruby Red,4488.086392,142.409830,373.680730,5034.036699
5,Burnt orange,4390.717769,180.018348,395.671699,5183.393757
14,Terra cotta,4134.025569,187.579435,606.873526,5123.729312
3,Brick red,4085.640876,221.816461,579.441307,5515.515628
9,Mauve,4022.220005,219.002804,437.448943,4596.216703
2,Black,3949.412323,184.047533,447.130418,5967.753644
0,Aubergine,3871.870890,183.322685,535.365322,5496.857753
10,Muted mustard yellow,3738.845968,414.240752,528.636958,4141.759758
7,Lavender,765.508099,2415.107493,4510.796536,457.958243
1,Baby blue,593.227172,3323.164454,3700.293473,1065.588157
11,Pale peach,552.774441,2605.645527,4186.164270,606.773268
16,White,501.874849,2742.029054,3732.205665,416.739427
8,Lemon yellow,390.238913,2498.674606,4361.671000,679.139574
15,Turquoise,386.693844,2288.848927,3802.282199,706.248205
12,Periwinkle,356.172835,2772.497070,4171.117938,381.836684
6,Fuchsia,228.087259,2231.083739,3890.229159,854.689492

In [37]:
'''The code below ranks the popularity of clothing items by color during the Spring season.'''
shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Color', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Spring', ascending = False)

Season,Color,Fall,Spring,Summer,Winter
1,Baby blue,593.227172,3323.164454,3700.293473,1065.588157
12,Periwinkle,356.172835,2772.497070,4171.117938,381.836684
16,White,501.874849,2742.029054,3732.205665,416.739427
11,Pale peach,552.774441,2605.645527,4186.164270,606.773268
8,Lemon yellow,390.238913,2498.674606,4361.671000,679.139574
7,Lavender,765.508099,2415.107493,4510.796536,457.958243
15,Turquoise,386.693844,2288.848927,3802.282199,706.248205
6,Fuchsia,228.087259,2231.083739,3890.229159,854.689492
10,Muted mustard yellow,3738.845968,414.240752,528.636958,4141.759758
3,Brick red,4085.640876,221.816461,579.441307,5515.515628
4,Brown,4549.173005,219.926643,187.804524,4453.445747
9,Mauve,4022.220005,219.002804,437.448943,4596.216703
14,Terra cotta,4134.025569,187.579435,606.873526,5123.729312
2,Black,3949.412323,184.047533,447.130418,5967.753644
0,Aubergine,3871.870890,183.322685,535.365322,5496.857753
5,Burnt orange,4390.717769,180.018348,395.671699,5183.393757
13,Ruby Red,4488.086392,142.409830,373.680730,5034.036699

In [ ]:
# Previous Purchases is unclear. We don't know if it was for the same user.
# We can work around this by aggregating information from multiple columns
# We don't know if the gender and age refer to individuals or groups
# For now, we will make a pivot table

shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Color', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Summer', ascending = False)

#This table shows the data is spread across four columns corresponding to the seasons of one year (Fall, Spring, Summer, Winter),
#and each season is treated as a singular categorical variable, not a sciding scale (timewise).

#The table also shows all colors present in the data, and therefore utilizd by the company in question.

Season,Color,Fall,Spring,Summer,Winter
7,Lavender,765.508099,2415.107493,4510.796536,457.958243
8,Lemon yellow,390.238913,2498.674606,4361.671000,679.139574
11,Pale peach,552.774441,2605.645527,4186.164270,606.773268
12,Periwinkle,356.172835,2772.497070,4171.117938,381.836684
6,Fuchsia,228.087259,2231.083739,3890.229159,854.689492
15,Turquoise,386.693844,2288.848927,3802.282199,706.248205
16,White,501.874849,2742.029054,3732.205665,416.739427
1,Baby blue,593.227172,3323.164454,3700.293473,1065.588157
14,Terra cotta,4134.025569,187.579435,606.873526,5123.729312
3,Brick red,4085.640876,221.816461,579.441307,5515.515628
0,Aubergine,3871.870890,183.322685,535.365322,5496.857753
10,Muted mustard yellow,3738.845968,414.240752,528.636958,4141.759758
2,Black,3949.412323,184.047533,447.130418,5967.753644
9,Mauve,4022.220005,219.002804,437.448943,4596.216703
5,Burnt orange,4390.717769,180.018348,395.671699,5183.393757
13,Ruby Red,4488.086392,142.409830,373.680730,5034.036699
4,Brown,4549.173005,219.926643,187.804524,4453.445747

In [ ]:
'''The code below ranks the popularity of clothing items by color during the Winter season.'''
shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Color', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Winter', ascending = False)

Season,Color,Fall,Spring,Summer,Winter
2,Black,3949.412323,184.047533,447.130418,5967.753644
3,Brick red,4085.640876,221.816461,579.441307,5515.515628
0,Aubergine,3871.870890,183.322685,535.365322,5496.857753
5,Burnt orange,4390.717769,180.018348,395.671699,5183.393757
14,Terra cotta,4134.025569,187.579435,606.873526,5123.729312
13,Ruby Red,4488.086392,142.409830,373.680730,5034.036699
9,Mauve,4022.220005,219.002804,437.448943,4596.216703
4,Brown,4549.173005,219.926643,187.804524,4453.445747
10,Muted mustard yellow,3738.845968,414.240752,528.636958,4141.759758
1,Baby blue,593.227172,3323.164454,3700.293473,1065.588157
6,Fuchsia,228.087259,2231.083739,3890.229159,854.689492
15,Turquoise,386.693844,2288.848927,3802.282199,706.248205
8,Lemon yellow,390.238913,2498.674606,4361.671000,679.139574
11,Pale peach,552.774441,2605.645527,4186.164270,606.773268
7,Lavender,765.508099,2415.107493,4510.796536,457.958243
16,White,501.874849,2742.029054,3732.205665,416.739427
12,Periwinkle,356.172835,2772.497070,4171.117938,381.836684

**Conclusions from code cells above: Purchase by season**
- For the Fall season, ***brown*** is the most commonly purchased color.
- For the Spring season, ***baby blue*** is the most commonly purchased color.
- For the Summer season, ***lavender*** is the most commonly purchased color.
- For the Winter season, ***black*** is the most commonly purchased color.

In [ ]:
# In the event that we might wish to analyze the data by region
# We see that all 50 states are accounted for

shopping_data['Location'].unique()

<StringArray>
[         'Maine',              nan,         'Nevada',       'Nebraska',
         'Oregon',     'California',      'Minnesota',     'Washington',
       'Colorado',        'Florida',          'Texas',       'Virginia',
       'Delaware',        'Wyoming',   'North Dakota',  'New Hampshire',
           'Utah',       'Kentucky',       'Michigan',      'Wisconsin',
     'New Mexico',    'Mississippi',  'West Virginia',      'Tennessee',
 'South Carolina',        'Alabama',   'Pennsylvania',         'Kansas',
         'Alaska',    'Connecticut',  'Massachusetts',       'Missouri',
           'Ohio',        'Montana',        'Georgia',     'New Jersey',
       'Maryland',           'Iowa',       'Illinois',        'Indiana',
        'Arizona',        'Vermont',          'Idaho',       'Oklahoma',
      'Louisiana',       'New York',   'South Dakota',       'Arkansas',
 'North Carolina',   'Rhode Island',         'Hawaii']
Length: 51, dtype: str

***Most popular items***

The four cells below consist of pivot tables that show the most commonly purchased item of clothing per season.

In [ ]:
'''This code cell displays the popularity of clothing items in Fall.'''

shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Item Purchased', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Fall', ascending = False).head()

Season Item Purchased         Fall  Spring  Summer       Winter
16            Sweater  3400.202243     NaN     NaN  5433.484402
14              Socks  3369.806336     NaN     NaN  4507.728562
0            Backpack  3203.718606     NaN     NaN  5747.170936
4              Gloves  3185.063060     NaN     NaN  5292.375153
10            Pajamas  3162.869105     NaN     NaN  5259.793350

In [ ]:
'''This code cell displays the popularity of clothing items in Spring.'''

shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Item Purchased', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Spring', ascending = False).head()

Season Item Purchased         Fall       Spring       Summer  Winter
11      Running Shoes  1167.144919  4225.224380  6418.953635     NaN
17            T-shirt   929.515627  3930.864173  5472.822985     NaN
5             Handbag  1528.874557  3770.964874  5357.561476     NaN
13             Shorts  1593.787910  3723.436858  6862.412862     NaN
15         Sunglasses  1814.473953  3713.580692  6202.873242     NaN

In [ ]:
'''This code cell displays the popularity of clothing items in Summer.'''

shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Item Purchased', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Summer', ascending = False).head()

Season Item Purchased         Fall       Spring       Summer  Winter
13             Shorts  1593.787910  3723.436858  6862.412862     NaN
11      Running Shoes  1167.144919  4225.224380  6418.953635     NaN
15         Sunglasses  1814.473953  3713.580692  6202.873242     NaN
3               Dress  1848.518614  3465.344382  6132.189466     NaN
17            T-shirt   929.515627  3930.864173  5472.822985     NaN

In [ ]:
'''This code cell displays the popularity of clothing items in Winter.'''

shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Item Purchased', columns = 'Season', aggfunc = 'sum').reset_index().sort_values('Winter', ascending = False).head()

Season Item Purchased         Fall  Spring  Summer       Winter
9            Leggings  2878.988382     NaN     NaN  6054.404063
0            Backpack  3203.718606     NaN     NaN  5747.170936
16            Sweater  3400.202243     NaN     NaN  5433.484402
4              Gloves  3185.063060     NaN     NaN  5292.375153
10            Pajamas  3162.869105     NaN     NaN  5259.793350

**RESULTS**

As we can see, the popularity of relevant items is such:
- **Fall**: Sweater
- **Spring**: Running shoes
- **Summer**: Shorts
- **Winter**: Leggings

***PROMO CODE EFFECT***

The code below is clarifying the effect of promo codes on the dollar amount of purchases.

In [63]:
shopping_data.groupby('Promo Code Used')['Purchase Amount (USD)'].mean()
# shopping_data.pivot_table(values = 'Purchase Amount (USD)', index = 'Item Purchased', columns = 'Promo Code', aggfunc = 'sum').reset_index().sort_values('No', ascending = False)

Promo Code Used
No     30.172085
Yes    50.023814
Name: Purchase Amount (USD), dtype: float64

***PROMO CODE CONCLUSION***

As we can tell, there is a notable difference in the purchase amount of all goods when promo codes are used, specifically regarding the difference in means.

***REVIEWS***

The code below is attempting to identify when users are most keen to leave a review.

In [87]:
shopping_data['Review Rating'].value_counts()

Review Rating
4.0    715
5.0    448
2.0    218
1.0     49
3.0      1
Name: count, dtype: int64

***REVIEWS CONCLUSION***

- The most common rating for products is a 4 star review.
- The second most common rating for products is a 5 star review.
- The third most common rating for products is a 2 star review.
- The fourth most common rating for products is a 1 star review.
- The least common rating for products is a 3 star review.